packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.13.6
  '@orpc/openapi': ^1.13.6
  '@orpc/server': ^1.13.6
  '@orpc/zod': ^1.13.6
  better-auth: ^1.5.1
  dotenv: ^17.3.1
  drizzle-orm: ^0.45.1
  next: ^16.1.6
  typescript: 5.9.3
  zod: ^4.3.6
