packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  next: ^16.1.1
  "@orpc/server": ^1.12.2
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  better-auth: ^1.4.18
