import {
  BookOpen,
  Building2,
  Globe,
  HardDrive,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Lock,
  Mail,
  Monitor,
  PenTool,
  RefreshCw,
  Server,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Star,
  Wrench,
  Zap,
} from "lucide-react";

const PRODUCT_ITEMS = [
  {
    category: "Hosting & Server",
    to: "/hosting",
    icon: Server,
    items: [
      {
        to: "/apps",
        label: "Instan Apps",
        icon: Layers,
        description: "Deploy n8n, Grafana, Typebot & 50+ aplikasi siap pakai dalam hitungan detik — tanpa konfigurasi manual.",
        badge: "BARU",
        isHiglighted: true,
      },
      {
        to: "/hosting",
        label: "Web Hosting",
        icon: Server,
        description: "Hosting SSD NVMe cepat dengan cPanel.",
        badge: "Promo",
        isHiglighted: false,
      },
      {
        to: "/vps",
        label: "VPS Cloud",
        icon: HardDrive,
        description: "Virtual server fleksibel skala enterprise.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/dedicated",
        label: "Dedicated Server",
        icon: Monitor,
        description: "Performa penuh tanpa berbagi resource.",
        badge: null,
        isHiglighted: false,
      },
     
    ],
  },
  {
    category: "Produk Digital",
    to: "/digital",
    icon: Layers,
    items: [
      {
        to: "/domain",
        label: "Registrasi Domain",
        icon: Globe,
        description: "Temukan & daftarkan nama domain terbaik.",
        badge: "Promo",
        isHiglighted: false,
      },
      {
        to: "/ssl-premium",
        label: "Sertifikat SSL Premium",
        icon: Lock,
        description: "Amankan website dengan SSL DV, OV, EV.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/business-email",
        label: "Email Bisnis",
        icon: Mail,
        description: "Email profesional dengan domain sendiri.",
        badge: "Populer",
        isHiglighted: false,
      },
      {
        to: "/lisensi",
        label: "Lisensi Software",
        icon: KeyRound,
        description: "Windows Server, cPanel, Plesk & lainnya.",
        badge: null,
        isHiglighted: false,
      },
    ],
  },
  {
    category: "Template Website",
    to: "/templates",
    icon: LayoutTemplate,
    items: [
      {
        to: "/templates/landing-page",
        label: "Landing Page",
        icon: LayoutTemplate,
        description: "Halaman pemasaran modern dengan konversi tinggi.",
        badge: "Populer",
        isHiglighted: false,
      },
      {
        to: "/templates/toko-online",
        label: "Toko Online",
        icon: ShoppingBag,
        description: "Toko siap jual dengan checkout & manajemen produk.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/templates/blog",
        label: "Blog & Majalah",
        icon: BookOpen,
        description: "Desain editorial bersih, cepat, dan SEO-ready.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/templates/bisnis",
        label: "Profil Bisnis",
        icon: Building2,
        description: "Website perusahaan profesional & mudah dikelola.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/templates/portfolio",
        label: "Portfolio",
        icon: Star,
        description: "Showcase karya kreatif yang berkesan & elegan.",
        badge: "Baru",
        isHiglighted: false,
      },
    ],
  },
  {
    category: "Layananan",
    to: "/services",
    icon: Wrench,
    items: [
      {
        to: "/services/custom-website",
        label: "Custom Website",
        icon: PenTool,
        description: "Website profesional dibangun dari nol sesuai kebutuhan bisnis Anda.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/services/perawatan-website",
        label: "Perawatan Website",
        icon: Wrench,
        description: "Update, backup rutin, keamanan, dan optimasi performa berkala.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/services/migrasi",
        label: "Migrasi Website",
        icon: RefreshCw,
        description: "Pindahkan website lama ke infrastruktur kami tanpa downtime.",
        badge: null,
        isHiglighted: false,
      },
      {
        to: "/services/konsultasi",
        label: "Konsultasi Teknis",
        icon: Settings,
        description: "Diskusi solusi teknologi terbaik bersama tim ahli kami — gratis.",
        badge: null,
        isHiglighted: false,
      },
    ],
  },
];

export { PRODUCT_ITEMS };
